### ISSUE TITLE
Issues not captured

### ISSUE THREAD

**Issue by Kamik423** [Aeron/Mypy.novaextension#1] opened 2021-03-04 10:56 UTC
Extension Console output in Nova

```
Mypy[11:54:10.797000] Running /Users/hans/.pyenv/shims/mypy simulator.py
Mypy[11:54:11.482000] Checking simulator.py
Mypy[11:54:11.482000] Found 0 issue(s)
```

Terminal output of same command

```
@ ~/D/Simulator> /Users/hans/.pyenv/shims/mypy simulator.py
simulator.py:107: error: Function is missing a return type annotation
simulator.py:107: note: Use "-> None" if function does not return a value
simulator.py:108: error: Name 'x' is not defined
Found 2 errors in 1 file (checked 1 source file)
```

I tried to dig into the source code but I could not quite find where the issue occurs as I am not too familiar with JS and the Nova API. I think somehow the capturing of stdout/stderr does not occur correctly.

**Comment by Aeron** [comment] 2021-03-04 13:24
Hey, thanks for letting me know.

I’ll look into it a bit later. Maybe the latest Nova updates changed something I let slip unnoticed. Although, it is the first such report since the last Nova update.

By the way, do you have a code example to verify this issue? A one where it reproduces accurately.

**Comment by Kamik423** [comment] 2021-03-04 20:15
It does not work for me in general. None of the issues in this specific file get reported:

```
#!/usr/bin/env python3


def my_function():
    print(x)


my_function()
```

regular Mypy output is

```
test.py:4: error: Function is missing a return type annotation
test.py:4: note: Use "-> None" if function does not return a value
test.py:5: error: Name 'x' is not defined
Found 2 errors in 1 file (checked 1 source file)
```

I am not sure what this is related to. Maybe it is because I am using fish as a shell? Could this potentially influence the plugin?

**Comment by Aeron** [comment] 2021-03-05 06:31
Thanks. I doubt that fish is the reason here since I’m also a fellow fish user 😄 I’ll check it ASAP.

**Comment by Aeron** [comment] 2021-03-24 19:05
@Kamik423, I tried to reproduce this behavior, but strangely, Mypy gave me the same result in all cases I checked: VS Code, bare Mypy, and Nova. In all cases, I checked with and without a configuration file. And I don’t have a global configuration file for Mypy.

My project-level configuration usually looks like this (and should not affect results):
```ini
[mypy]
ignore_missing_imports = True
follow_imports = silent
show_column_numbers = True
warn_redundant_casts = True
sqlite_cache = True
```

The result always was “Success: no issues found in 1 source file”. But something similar to the behavior you have I was able to reproduce with the `--strict` option. It looks like the following:
```
playground-3.py:4:1: error: Function is missing a return type annotation
playground-3.py:4:1: note: Use "-> None" if function does not return a value
playground-3.py:5:11: error: Name 'x' is not defined
playground-3.py:8:1: error: Call to untyped function "my_function" in typed context
Found 3 errors in 1 file (checked 1 source file)
```

So, do you have a global configuration file for Mypy maybe somewhere, like `$XDG_CONFIG_HOME/mypy/config` or `~/.config/mypy/config` or `~/.mypy.ini`, by any chance? But beyond those, Mypy will always prioritize a project- or directory-level configuration file, like `mypy.ini` then `.mypy.ini`, and finally `setup.cfg`. Maybe there’s an option somewhere that works for bare use yet not visible for the extension.

Also, the version of Mypy I’m using is `0.812`, just in case. Which one do you use?

For example, Flake8 always sees the undefined `x` error, the obvious and only real one here (since other errors exist only for the strict mode). Yet my Mypy version sees nothing in this case, and I’m not sure it has to, without some particular options.

To be precise (since the strict option is an alias for a set of flags), the following flags will produce a result like above:
- The `--disallow-untyped-calls` for `error: Call to untyped function "my_function" in typed context`;
- The `--disallow-untyped-defs` for `error: Function is missing a return type annotation` and `note: Use "-> None" if function does not return a value`;
- And the `--check-untyped-defs` for `error: Name 'x' is not defined`.

By default, all of those are disabled (or ignored).

My assumption here is that you use an older Mypy version, where some of those options are possibly enabled, or it’s some inconsistencies between global and local configurations. The first one is unlikely since it looks like you’re using the same Mypy (from your Pyenv) in both cases.

**Comment by Kamik423** [comment] 2021-04-17 13:24
Unfortunately I was only using the trial version of Nova and have decided not to continue on to the paid one, so I cannot help you further. I hope no one else encounters the issue though.

**Comment by Aeron** [comment] 2021-04-22 03:44
@Kamik423, no worries, and thank you for the report anyway. Maybe it’ll help in the future. (Closing it for now.)

**Closed as completed by Aeron** 2021-04-22 03:44 UTC
